#pragma once

// Modifying THIS PARTICULAR file requires ALL code to rebuild, so make 
// all your edits here early in your development time.

// Defines trading cards.
enum TradingCardTypes
{
	CARD_INVALID = -1,
	CARD_NAVAL_MOVES,
	CARD_FISH_GOLD,
	CARD_RANDOM_SPY,
	CARD_ANCIENT_UNITS_FAVORABLE_WINDS,
	CARD_ANCIENT_UNITS_SACRIFICIAL_CAPTIVES,
	CARD_ANCIENT_UNITS_MILITIA,
	CARD_ANCIENT_UNITS_OBSIDIAN_ARROWS,
	CARD_ANCIENT_UNITS_WAY_OF_THE_WARRIOR,
	CARD_ANCIENT_UNITS_SCOUTING,
	CARD_ANCIENT_UNITS_SLAVES,
	CARD_ANCIENT_UNITS_GREEK_FIRE,
	CARD_ANCIENT_UNITS_BRONZE_CLAD_HULL,
	CARD_ANCIENT_UNITS_SPOKED_WHEELS,
	CARD_ANCIENT_UNITS_SHIELD_WALL,
	CARD_ANCIENT_UNITS_VALOUR,
	CARD_ANCIENT_RESOURCES_INUITS,
	CARD_ANCIENT_RESOURCES_BEDOUINS,
	CARD_ANCIENT_RESOURCES_ATLATL,
	CARD_ANCIENT_RESOURCES_FLINT_KNAPPING,
	CARD_ANCIENT_RESOURCES_SACRIFICIAL_LAMBS,
	CARD_ANCIENT_RESOURCES_SPEAR_FISHING,
	CARD_ANCIENT_RESOURCES_DIVINE_CREATION,
	CARD_ANCIENT_BUILDINGS_SHIPS_OF_THE_DESERT,
	CARD_ANCIENT_BUILDINGS_FORCED_LEVY,
	CARD_ANCIENT_POLITICAL_ORTHODOXY,
	CARD_ANCIENT_POLITICAL_PROGRESSIVE,
	CARD_ANCIENT_POLITICAL_AGGRESIVE,
	CARD_ANCIENT_POLITICAL_EXCLUSIVE,
	CARD_ANCIENT_POLITICAL_PROTECTIVE,
	CARD_ANCIENT_BUILDINGS_DRUIDS,
	CARD_ANCIENT_BUILDINGS_HARBORMASTER,



	CARD_NUM,
};

