#pragma once

// Modifying THIS PARTICULAR file requires ALL code to rebuild, so make 
// all your edits here early in your development time.

// Defines trading cards.
enum TradingCardTypes
{
	CARD_INVALID = -1,
	CARD_NAVAL_MOVES,
	CARD_FISH_GOLD,
	CARD_RANDOM_SPY,
	CARD_ANCIENT_UNITS_FAVORABLE_WINDS,
	CARD_ANCIENT_UNITS_SACRIFICIAL_CAPTIVES,
	CARD_ANCIENT_UNITS_MILITIA,
	CARD_ANCIENT_UNITS_OBSIDIAN_ARROWS,
	CARD_ANCIENT_UNITS_WAY_OF_THE_WARRIOR,
	CARD_ANCIENT_UNITS_SCOUTING,
	CARD_ANCIENT_UNITS_SLAVES,
	CARD_ANCIENT_UNITS_GREEK_FIRE,
	CARD_ANCIENT_UNITS_BRONZE_CLAD_HULL,
	CARD_ANCIENT_UNITS_SPOKED_WHEELS,
	CARD_ANCIENT_UNITS_SHIELD_WALL,
	CARD_ANCIENT_UNITS_VALOUR,
	CARD_NUM,
};

